#!/bin/bash

flatpak install --system -y --noninteractive flathub \
    org.mozilla.firefox \
    com.google.Chrome \
    com.visualstudio.code \
    de.wagnermartin.Plattenalbum \
    md.obsidian.Obsidian \
    org.gnome.Evolution \
    org.gnome.Calculator \
    com.github.tchx84.Flatseal \
    org.keepassxc.KeePassXC \
    org.telegram.desktop \
    org.gnome.World.Secrets \
    com.mongodb.Compass \
    io.beekeeperstudio.Studio \
    fr.free.Homebank &&

sudo rm -fr /post