#!/bin/bash
## ndbe



## hostname
sleep 1
clear
echo "level 1"
ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime &&
hwclock --systohc &&
timedatectl set-ntp true &&
timedatectl set-timezone Asia/Jakarta &&
timedatectl status &&
timedatectl show-timesync --all &&
systemctl enable systemd-timesyncd.service &&



## locale
sleep 1
clear
echo "level 2"
locale-gen  &&


## administrator
sleep 1
clear
echo "level 3"
rm /etc/skel/.bash* &&
useradd -d /var/usr loki &&
chown -R loki:loki /var/usr &&
passwd loki &&
chmod 700 /var/usr/.ssh/ &&
chmod 600 /var/usr/.ssh/authorized_keys &&
sudo chattr +i .ssh/authorized_keys &&
usermod -aG wheel loki &&


## virtualmin
sleep 1
clear
echo "level 4"
useradd -d /var/games -u 50 -g games games &&
passwd -l games &&


## application
sleep 1
clear
echo "level 5"
mkdir -p /opt/flat &&
ln -sf /opt/flat /var/lib/flatpak &&
pacstrap /mnt flatpak gnome-software --noconfirm &&


## aide hids
sleep 1
clear
echo "level 6"
pkg-config --libs --cflags glib-2.0 &&
cd /tmp &&
wget https://github.com/aide/aide/releases/download/v0.19.2/aide-0.19.2.tar.gz  &&
sudo tar -xf aide-0.19.2.tar.gz &&
cd aide-0.19.2 &&
sudo ./configure --with-zlib --with-posix-acl --with-xattr --with-curl --with-locale --with-syslog-ident --with-config-file=/etc/aide.conf &&
sudo make && make install &&
mkdir -p /var/lib/aide &&


## boot config
sleep 1
clear
echo "level 7"
rm -fr /etc/mkinitcpio.conf.d &&
rm /boot/initramfs-linux-hardened* &&
mkdir -p /boot/efi /boot/efi/linux /boot/efi/systemd /boot/efi/rescue /boot/efi/boot /boot/kernel &&
mv /boot/*-ucode.img /boot/vmlinuz-linux-hardened /boot/kernel &&


## service activation
sleep 1
clear
echo "level 8"
systemctl enable systemd-timesyncd.service &&
systemctl enable tangd.socket &&
systemctl enable apparmor.service &&
systemctl enable sshd &&
systemctl enable update.timer &&
systemctl enable prometheus.service &&
systemctl enable prometheus-node-exporter.service &&
systemctl enable irqbalance &&
systemctl enable tuned &&
systemctl enable tuned-ppd.service &&
systemctl enable nginx &&
systemctl enable systemd-networkd &&
systemctl enable systemd-resolved &&
systemctl enable aide.timer &&
systemctl enable sddm &&
systemctl enable --global gcr-ssh-agent.socket &&
systemctl enable --global hypridle.service &&
systemctl enable --global hyprpolkitagent &&
systemctl enable --global waybar &&
systemctl enable --global pipewire-pulse &&
systemctl enable clevis-luks-askpass.path